---
title: "Tidying `dadmom`"
author: "Angel Salazar"
output: github_document
---

# Get the data

```{r}
# don't modify this chunk unless you still need to install rcfss
# if so, run "devtools::install_github("uc-cfss/rcfss")" in the console first

library(tidyverse)
library(rcfss)

data("dadmom")
dadmom
```

# Tidied data

```{r}
# write your code to tidy the data here
# store your tidied data frame as dadmom_tidy
dadmom_tidy <- dadmom %>%
  unite (d, named, incd) %>%
  unite (m, namem, incm) %>%
  pivot_longer (c("d","m"), names_to = "parent", values_to = "name") %>%
  separate (name, into = c("name","inc"), convert = TRUE)
  
# print the contents
dadmom_tidy
```

# Plot the data

```{r}
######### DO NOT MODIFY THIS CODE CHUNK. IF YOU TIDIED THE DATA CORRECTLY
######### IT SHOULD JUST WORK.
# parent: m or d
# inc: individual income
# famid: family ID
ggplot(data = dadmom_tidy, mapping = aes(x = parent, y = inc)) +
  geom_point() +
  geom_line(mapping = aes(group = famid)) +
  scale_y_continuous(labels = scales::dollar) +
  labs(
    title = "Gender parity and household income",
    subtitle = "Each line identifies a distinct family",
    x = "Mom or Dad",
    y = "Income",
  ) +
  theme_minimal()
```

## Session info

```{r, echo = TRUE}
# don't modify this chunk
devtools::session_info()
```


